#!/usr/bin/env node
/**
 * configure-build.js
 *
 * Interactive plugin selector for BizFlow builds.
 * Prompts you to choose which plugins to bundle, then writes .env.build.
 *
 * Usage:
 *   node scripts/configure-build.js
 *   npm run build:configure
 *
 * After running this, execute `npm run build` (or any build:* variant).
 * The Vite config and merge-schemas.js both read .env.build automatically.
 */

const fs = require('fs')
const path = require('path')
const readline = require('readline')

const ROOT = path.resolve(__dirname, '..')
const PLUGINS_DIR = path.join(ROOT, 'src', 'plugins')
const ENV_BUILD = path.join(ROOT, '.env.build')

// ── Discover available plugins ─────────────────────────────────────────────
const allPlugins = fs
  .readdirSync(PLUGINS_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory() && fs.existsSync(path.join(PLUGINS_DIR, d.name, 'schema.prisma')))
  .map((d) => d.name)

if (allPlugins.length === 0) {
  console.log('No plugins with a schema.prisma found in src/plugins/. Nothing to configure.')
  process.exit(0)
}

// ── Read existing .env.build for defaults ─────────────────────────────────
function readCurrentlyEnabled() {
  if (!fs.existsSync(ENV_BUILD)) return allPlugins  // default: all enabled
  const match = fs.readFileSync(ENV_BUILD, 'utf-8').match(/^ENABLED_MODULES=(.+)$/m)
  return match ? match[1].split(',').map((s) => s.trim()) : allPlugins
}

// ── Interactive prompt ─────────────────────────────────────────────────────
async function prompt(rl, question) {
  return new Promise((resolve) => rl.question(question, resolve))
}

async function main() {
  console.log('\n╔══════════════════════════════════════════╗')
  console.log('║   BizFlow — Build-time Plugin Selection  ║')
  console.log('╚══════════════════════════════════════════╝\n')
  console.log('Choose which plugins to include in this build.')
  console.log('Excluded plugins will be completely removed from the bundle.\n')

  const currentlyEnabled = readCurrentlyEnabled()
  const selected = []

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout })

  for (const plugin of allPlugins) {
    const defaultAnswer = currentlyEnabled.includes(plugin) ? 'Y' : 'N'
    const answer = await prompt(rl, `  Include plugin "${plugin}"? [${defaultAnswer}] `)
    const include = answer.trim() === '' ? defaultAnswer : answer.trim().toUpperCase()
    if (include === 'Y' || include === 'YES') selected.push(plugin)
  }

  rl.close()

  if (selected.length === 0) {
    console.error('\n⚠  No plugins selected — at least one plugin must be included.')
    process.exit(1)
  }

  // Write .env.build
  const envContent = `# Generated by scripts/configure-build.js — do not commit!\nENABLED_MODULES=${selected.join(',')}\n`
  fs.writeFileSync(ENV_BUILD, envContent, 'utf-8')

  console.log(`\n✓  .env.build written with: ENABLED_MODULES=${selected.join(',')}`)
  console.log('   Run "npm run build" (or build:win / build:linux / build:mac) to build.\n')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
